import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import UpperNavbar from "@/Components/UpperNavbar";
import Navbar from "@/Components/Navbar";
import NextProviderAuth from "@/Providers/NextProviderAuth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextProviderAuth>
          <UpperNavbar />
          <Navbar />
          <main>{children}</main>
        </NextProviderAuth>
      </body>
    </html>
  );
}
